version: '3'
services:
  web:
    image: nginx
    #из локального копирует в гостевую
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - 8080:80
    restart: always
    depends_on:
      - php-fpm
      - db
  php-fpm:
    build:
      context: ./
      dockerfile: docker/php-fpm.docker
    restart: always
    volumes:
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - .:/var/www/html

  db:
    image: postgres:10.1
    restart: always
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5432:5432