version: '3.2'
services:
  nginx:
    build:
      context: ./
      dockerfile: docker/nginx.docker
    volumes:
    - ./:/var/www
    ports:
    - "8080:80"
    links:
      - php-fpm

  php-fpm:
    build:
      context: ./
      dockerfile: docker/php-fpm.docker
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=5432"
      - "DB_HOST=db"
    links:
      - db

  db:
    image: postgres:10.1
    volumes:
    - ./storage/docker/postgres:/var/lib/postgres
    environment:
    - POSTGRES_USER=testuser
    - POSTGRES_PASSWORD=qwerty
    ports:
    - "5432:5432"